# Javascript Node CircleCI configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:11.0.2-jdk-node

orbs:
  win: circleci/windows@2.4.0 # The Windows orb give you everything you need to start using the Windows executor.
  release-management: salesforce/npm-release-management@3.5.1
  codecov: codecov/codecov@1.1.1

jobs:
  windows-tests:
    executor:
      name: win/default # executor type
      size: "medium"
    working_directory: C:\repo
    steps:
      - checkout
      - run: ./gradlew build

workflows:
  version: 2.1
  test-publish:
    jobs:
      - windows-tests:
          filters:
            tags:
              only: /.*/
